apiVersion: v1
kind: Service
metadata:
  name: argocd-helloworld
spec:
  selector:
    app: argocd-helloworld
  ports:
  - name: http
    nodePort: 31806
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort